# docker compose in case you want to run production build locally
version: "3"
services:
    laravel.production:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.production
        ports:
            - "${APP_PORT:-80}:80"
